[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
purpose_challenge = "3qJ7i6VosNpuJieRHAywaLjEo8JacU8RSkhxuuG3tPq3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "user.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
